### ISSUE TITLE
Allow integrating ep_hash_auth into Etherpad?

### ISSUE THREAD

**Issue by muxator** [ether/ep_hash_auth#4]
@Laking, would you agree to donate **ep_hash_auth** to allow its integration into Etherpad's codebase?

**Comment by LaKing** [comment]
@muxator Yes, of course!

**Comment by muxator** [comment]
Many thanks @LaKing.

Once the integration is complete, a final update on the plugin to mention its obsolescence will problably be needed. I will reach out to you for doing this, push a final update on npm and close this issue.

Bye!

**Comment by LaKing** [comment]
There was a contribution with additional types. Merged.

**Comment by JohnMcLear** [comment]
@LaKing can you make me an owner of this repo please? :)

**Comment by LaKing** [comment]
@JohnMcLear 

Ye, .. I'm just a noob and didn't figure out yet how to do it properly, always get some errors.
I added johnyma22 but failed at transferring ...

**Comment by JohnMcLear** [comment]
ha, well @johnmclear not @johnyma22 for the repo btw :)

**Comment by LaKing** [comment]
It says: user JohnMcLear not found

**Comment by JohnMcLear** [comment]
On Github?  Weird ...

johnyma22 on npm
johnmclear on github..

**Comment by LaKing** [comment]
Please keep a note about the history of the project .)

**Comment by JohnMcLear** [comment]
Oh defo :)  Also, we should add me as owner on npm so I can publish or did we do that already?

**Comment by JohnMcLear** [comment]
Okay looks good RE github we're in the foundations organization now.
